package fabricops

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// DockerConfig holds parameters for generating a node's docker-compose.yaml.
type DockerConfig struct {
	NetworkName      string
	NetworkDomain    string
	OrgName          string
	MSPID            string
	Domain           string
	PeerPort         int
	ChaincodePort    int
	OpsPort          int
	CouchDBPort      int
	OrdererPort      int               // orderer listen port (default 7050)
	OrdererAdminPort int               // osnadmin port (default 7053)
	OrdererOpsPort   int               // orderer operations port (default 9443)
	GossipAddr       string            // host:port of a bootstrap peer for gossip
	IncludeOrderer   bool              // true for bootstrap node
	ExtraHosts       map[string]string // hostname → IP for cross‐host resolution
}

const bootstrapComposeTmpl = `# Auto-generated by kufichain — do not edit manually
networks:
  kufichain:
    name: kufichain_network
    external: true

volumes:
  orderer.{{.NetworkDomain}}:
  peer0.{{.Domain}}:
  couchdb.{{.OrgName | lower}}:

services:
  orderer.{{.NetworkDomain}}:
    hostname: orderer.{{.NetworkDomain}}
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabriccfg
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/{{.NetworkDomain}}/orderers/orderer.{{.NetworkDomain}}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/{{.NetworkDomain}}/orderers/orderer.{{.NetworkDomain}}/tls:/var/hyperledger/orderer/tls
      - orderer.{{.NetworkDomain}}:/var/hyperledger/production/orderer
      - ./config:/etc/hyperledger/fabriccfg
{{- if .ExtraHosts}}
    extra_hosts:
{{- range $host, $ip := .ExtraHosts}}
      - "{{$host}}:{{$ip}}"
{{- end}}
{{- end}}
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - kufichain

  peer0.{{.Domain}}:
    hostname: peer0.{{.Domain}}
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.{{.Domain}}
      - CORE_PEER_ADDRESS=peer0.{{.Domain}}:{{.PeerPort}}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:{{.PeerPort}}
      - CORE_PEER_CHAINCODEADDRESS=peer0.{{.Domain}}:{{.ChaincodePort}}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:{{.ChaincodePort}}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.{{.Domain}}:{{.PeerPort}}
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
{{- if .GossipAddr}}
      - CORE_PEER_GOSSIP_BOOTSTRAP={{.GossipAddr}}
{{- end}}
      - CORE_PEER_LOCALMSPID={{.MSPID}}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:{{.OpsPort}}
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.{{.OrgName | lower}}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdbpw
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0{{.OrgName | lower}}"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GATEWAY_ENABLED=true
      - CORE_PEER_GATEWAY_CONCURRENCYLIMIT=500
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kufichain_network
    volumes:
      - ./crypto-config/peerOrganizations/{{.Domain}}/peers/peer0.{{.Domain}}:/etc/hyperledger/fabric
      - peer0.{{.Domain}}:/var/hyperledger/production
      - ./config:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
{{- if .ExtraHosts}}
    extra_hosts:
{{- range $host, $ip := .ExtraHosts}}
      - "{{$host}}:{{$ip}}"
{{- end}}
{{- end}}
    ports:
      - {{.PeerPort}}:{{.PeerPort}}
      - {{.OpsPort}}:{{.OpsPort}}
    depends_on:
      couchdb.{{.OrgName | lower}}:
        condition: service_healthy
{{- if .IncludeOrderer}}
      orderer.{{.NetworkDomain}}:
        condition: service_started
{{- end}}
    networks:
      - kufichain

  couchdb.{{.OrgName | lower}}:
    hostname: couchdb.{{.OrgName | lower}}
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdbpw
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5984/_up || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - couchdb.{{.OrgName | lower}}:/opt/couchdb/data
    ports:
      - {{.CouchDBPort}}:5984
    networks:
      - kufichain
`

const peerOnlyComposeTmpl = `# Auto-generated by kufichain — do not edit manually
networks:
  kufichain:
    name: kufichain_network
    external: true

volumes:
  peer0.{{.Domain}}:
  couchdb.{{.OrgName | lower}}:

services:
  peer0.{{.Domain}}:
    hostname: peer0.{{.Domain}}
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.{{.Domain}}
      - CORE_PEER_ADDRESS=peer0.{{.Domain}}:{{.PeerPort}}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:{{.PeerPort}}
      - CORE_PEER_CHAINCODEADDRESS=peer0.{{.Domain}}:{{.ChaincodePort}}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:{{.ChaincodePort}}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.{{.Domain}}:{{.PeerPort}}
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
{{- if .GossipAddr}}
      - CORE_PEER_GOSSIP_BOOTSTRAP={{.GossipAddr}}
{{- end}}
      - CORE_PEER_LOCALMSPID={{.MSPID}}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:{{.OpsPort}}
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.{{.OrgName | lower}}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdbpw
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0{{.OrgName | lower}}"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GATEWAY_ENABLED=true
      - CORE_PEER_GATEWAY_CONCURRENCYLIMIT=500
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kufichain_network
    volumes:
      - ./crypto-config/peerOrganizations/{{.Domain}}/peers/peer0.{{.Domain}}:/etc/hyperledger/fabric
      - peer0.{{.Domain}}:/var/hyperledger/production
      - ./config:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
{{- if .ExtraHosts}}
    extra_hosts:
{{- range $host, $ip := .ExtraHosts}}
      - "{{$host}}:{{$ip}}"
{{- end}}
{{- end}}
    ports:
      - {{.PeerPort}}:{{.PeerPort}}
      - {{.OpsPort}}:{{.OpsPort}}
    depends_on:
      couchdb.{{.OrgName | lower}}:
        condition: service_healthy
    networks:
      - kufichain

  couchdb.{{.OrgName | lower}}:
    hostname: couchdb.{{.OrgName | lower}}
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdbpw
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5984/_up || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - couchdb.{{.OrgName | lower}}:/opt/couchdb/data
    ports:
      - {{.CouchDBPort}}:5984
    networks:
      - kufichain
`

var funcMap = template.FuncMap{
	"lower": toLower,
}

// ordererOnlyComposeTmpl is for a dedicated orderer node — no peer or CouchDB.
const ordererOnlyComposeTmpl = `# Auto-generated by kufichain — do not edit manually
networks:
  kufichain:
    name: kufichain_network
    external: true

volumes:
  orderer.{{.NetworkDomain}}:

services:
  orderer.{{.NetworkDomain}}:
    hostname: orderer.{{.NetworkDomain}}
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabriccfg
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT={{.OrdererPort}}
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:{{.OrdererAdminPort}}
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:{{.OrdererOpsPort}}
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/{{.NetworkDomain}}/orderers/orderer.{{.NetworkDomain}}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/{{.NetworkDomain}}/orderers/orderer.{{.NetworkDomain}}/tls:/var/hyperledger/orderer/tls
      - orderer.{{.NetworkDomain}}:/var/hyperledger/production/orderer
      - ./config:/etc/hyperledger/fabriccfg
{{- if .ExtraHosts}}
    extra_hosts:
{{- range $host, $ip := .ExtraHosts}}
      - "{{$host}}:{{$ip}}"
{{- end}}
{{- end}}
    ports:
      - {{.OrdererPort}}:{{.OrdererPort}}
      - {{.OrdererAdminPort}}:{{.OrdererAdminPort}}
      - {{.OrdererOpsPort}}:{{.OrdererOpsPort}}
    networks:
      - kufichain
`

func toLower(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'A' && c <= 'Z' {
			b[i] = c + 32
		}
	}
	return string(b)
}

// GenerateBootstrapCompose creates docker-compose.yaml for orderer + peer + couchdb.
func GenerateBootstrapCompose(deployDir string, cfg DockerConfig) error {
	cfg.IncludeOrderer = true
	return renderCompose(deployDir, bootstrapComposeTmpl, cfg)
}

// GeneratePeerCompose creates docker-compose.yaml for a joining peer + couchdb only.
func GeneratePeerCompose(deployDir string, cfg DockerConfig) error {
	cfg.IncludeOrderer = false
	return renderCompose(deployDir, peerOnlyComposeTmpl, cfg)
}

// GenerateOrdererCompose creates docker-compose.yaml for a dedicated orderer only.
func GenerateOrdererCompose(deployDir string, cfg DockerConfig) error {
	if cfg.OrdererPort == 0 {
		cfg.OrdererPort = 7050
	}
	if cfg.OrdererAdminPort == 0 {
		cfg.OrdererAdminPort = 7053
	}
	if cfg.OrdererOpsPort == 0 {
		cfg.OrdererOpsPort = 9443
	}
	return renderCompose(deployDir, ordererOnlyComposeTmpl, cfg)
}

func renderCompose(deployDir, tmplText string, cfg DockerConfig) error {
	tmpl, err := template.New("compose").Funcs(funcMap).Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse compose template: %w", err)
	}

	path := filepath.Join(deployDir, "docker-compose.yaml")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, cfg)
}

// EnsureDockerNetwork creates the shared kufichain_network if it doesn't exist.
// All compose files reference this as external, so it must exist before any
// docker compose up.
func EnsureDockerNetwork() error {
	// Check if network already exists
	out, _ := exec.Command("docker", "network", "ls", "--filter", "name=^kufichain_network$", "--format", "{{.Name}}").Output()
	if strings.TrimSpace(string(out)) == "kufichain_network" {
		return nil // already exists
	}
	cmd := exec.Command("docker", "network", "create", "kufichain_network")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// composeProjectName derives a unique Docker Compose project name from the deploy
// directory path. This prevents cross-contamination when multiple nodes (orderer,
// peer1, peer2…) each have a "deploy" subdirectory on the same machine.
// Example: /path/.orderer/deploy → "kufi-orderer", /path/.peer1/deploy → "kufi-peer1"
func composeProjectName(deployDir string) string {
	parent := filepath.Dir(deployDir)
	base := filepath.Base(parent)
	base = strings.TrimPrefix(base, ".")
	if base == "" || base == "." {
		base = "default"
	}
	return "kufi-" + base
}

// StartContainers ensures the shared network exists, then runs docker compose up -d.
func StartContainers(deployDir string) error {
	if err := EnsureDockerNetwork(); err != nil {
		return fmt.Errorf("ensure docker network: %w", err)
	}
	p := composeProjectName(deployDir)
	return runCmd(deployDir, "docker", "compose", "-p", p, "up", "-d", "--remove-orphans")
}

// CleanupContainers tears down any existing containers and volumes.
func CleanupContainers(deployDir string) error {
	composePath := filepath.Join(deployDir, "docker-compose.yaml")
	if _, err := os.Stat(composePath); err != nil {
		return nil // no compose file, nothing to clean
	}
	p := composeProjectName(deployDir)
	return runCmd(deployDir, "docker", "compose", "-p", p, "down", "-v", "--remove-orphans")
}

// StopContainers runs docker compose down in the deploy directory.
func StopContainers(deployDir string) error {
	p := composeProjectName(deployDir)
	return runCmd(deployDir, "docker", "compose", "-p", p, "down", "--remove-orphans")
}

// CleanupLegacyNamedPeerContainers removes old fixed-name containers from
// previous kufichain versions to avoid conflicts with compose-managed names.
func CleanupLegacyNamedPeerContainers(domain, orgName string) {
	legacy := []string{
		fmt.Sprintf("peer0.%s", domain),
		fmt.Sprintf("couchdb.%s", toLower(orgName)),
	}
	for _, name := range legacy {
		_ = exec.Command("docker", "rm", "-f", name).Run()
	}
}

// ContainersRunning checks if the compose project already has running containers.
// Returns a list of running container names.
func ContainersRunning(deployDir string) []string {
	composePath := filepath.Join(deployDir, "docker-compose.yaml")
	if _, err := os.Stat(composePath); err != nil {
		return nil
	}
	p := composeProjectName(deployDir)
	out, err := runCmdOutput(deployDir, "docker", "compose", "-p", p, "ps", "--format", "{{.Name}}")
	if err != nil {
		return nil
	}
	var names []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			names = append(names, line)
		}
	}
	return names
}

// ContainerStatus runs docker compose ps in the deploy directory.
func ContainerStatus(deployDir string) (string, error) {
	p := composeProjectName(deployDir)
	out, err := runCmdOutput(deployDir, "docker", "compose", "-p", p, "ps", "--format", "table")
	return string(out), err
}

// WaitForService polls docker compose until a service container is running.
func WaitForService(deployDir, service string, maxWait int) error {
	if maxWait <= 0 {
		maxWait = 1
	}
	p := composeProjectName(deployDir)
	var lastErr error
	for i := 0; i < maxWait; i++ {
		out, err := runCmdOutput(deployDir, "docker", "compose", "-p", p, "ps", "-q", service)
		if err == nil {
			containerID := strings.TrimSpace(string(out))
			if containerID != "" {
				stOut, inspectErr := runCmdOutput(".", "docker", "inspect", "-f", "{{.State.Status}}", containerID)
				if inspectErr == nil {
					status := strings.TrimSpace(string(stOut))
					if status == "running" {
						return nil
					}
					if status == "exited" || status == "dead" {
						return fmt.Errorf("service %s container %s", service, status)
					}
				} else {
					lastErr = inspectErr
				}
			}
		} else {
			lastErr = err
		}
		time.Sleep(1 * time.Second)
	}
	if lastErr == nil {
		lastErr = fmt.Errorf("service not started")
	}
	return fmt.Errorf("service %s not running after %ds: %w", service, maxWait, lastErr)
}

// WaitForContainer polls docker until a container reports healthy/running.
func WaitForContainer(name string, maxWait int) error {
	for i := 0; i < maxWait; i++ {
		out, _ := runCmdOutput(".", "docker", "inspect", "-f", "{{.State.Status}}", name)
		status := strings.TrimSpace(string(out))
		if status == "running" {
			return nil
		}
		if status == "exited" || status == "dead" {
			return fmt.Errorf("container %s %s", name, status)
		}
		time.Sleep(1 * time.Second)
	}
	return fmt.Errorf("container %s not running after %ds", name, maxWait)
}
